version: '3.8'
services:

  <%= appname %>-db:
    image: postgres:15-alpine
    container_name: <%= appname %>-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: <%= appname %>-db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U docker -d <%= appname %>-db' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  pgadmin_data:
